package DAO;

import Util.ConnectionUtil;
import Model.Account;

import java.sql.*;

/** 
 * A DAO that mediates the transformation of data between the format of objects in Java to rows in the 
 * pre-created Account database.
 */
public class AccountDAO {
    private static AccountDAO accountDAO = null;

    private AccountDAO() {}

    public static AccountDAO  instance() {
        if (accountDAO == null) {
            accountDAO = new AccountDAO();
        }

        return accountDAO;
    }

    /** 
     * Inserts an account into the account table.
     * 
     * @param username username of account.
     * @param password password of account.
     * @return the newly created account object.
     */
    public Account registerAccount(Account account) {
        Connection connection = ConnectionUtil.getConnection();
        try {
            // Account ID will be automatically generated by the database.
            String sql = "INSERT INTO account (username, password) VALUES(?, ?)";
            PreparedStatement preparedStatement = connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);

            preparedStatement.setString(1, account.getUsername());
            preparedStatement.setString(2, account.getPassword());

            preparedStatement.executeUpdate();
            ResultSet pkeyResultSet = preparedStatement.getGeneratedKeys();
            if(pkeyResultSet.next()){
                int generated_account_id = (int) pkeyResultSet.getLong(1);
                return new Account(generated_account_id, account.getUsername(), account.getPassword());
            }

        } catch(SQLException e){
            System.out.println(e.getMessage());
        }

        return null;
    }

    /** 
     * Login to a account from the account table.
     * 
     * @param account the account object containing the credentials.
     * @return the account object.
     */
    public Account loginToAccount(Account account) {
        Connection connection = ConnectionUtil.getConnection();
        try {
            String sql = "SELECT * FROM account AS a WHERE a.username = ? AND a.password = ?";
            
            PreparedStatement preparedStatement = connection.prepareStatement(sql);

            preparedStatement.setString(1, account.getUsername());
            preparedStatement.setString(2, account.getPassword());

            ResultSet rs = preparedStatement.executeQuery();
            while(rs.next()){
                Account acc = new Account(rs.getInt("account_id"), rs.getString("username"), rs.getString("password"));
                return acc;
            }
        } catch(SQLException e){
            System.out.println(e.getMessage());
        }

        return null;
    }

    /**
     * Verify that user exists in account database.
     * 
     * @param account_id 
     * @return whether the user exists
     */
    public boolean accountExists(int account_id) {
        Connection connection = ConnectionUtil.getConnection();
        try {
            String sql = "SELECT * FROM account AS a WHERE a.account_id = ?";
            
            PreparedStatement preparedStatement = connection.prepareStatement(sql);

            preparedStatement.setInt(1, account_id);

            ResultSet rs = preparedStatement.executeQuery();
            while(rs.next()){
                return true;
            }
        } catch(SQLException e){
            System.out.println(e.getMessage());
        }

        return false;
    }

}